-- Migration manuelle (PostgreSQL / pgAdmin) — pas de Flyway (cf. CLAUDE.md).
-- Contexte : D2 — l'ID d'une demande de retrait devient AUTO-GÉNÉRÉ côté SGBD (comme t_verification).
-- t_demande_retrait.ID_DEMANDE_RETRAIT passe en colonne IDENTITY. Table vide (0 ligne) → pas de
-- migration de données ; la séquence est auto-dimensionnée (RESTART à MAX+1, soit 1).
-- À appliquer AVANT le déploiement du code @GeneratedValue.

DO $$
DECLARE nextid bigint;
BEGIN
    ALTER TABLE t_demande_retrait
        ALTER COLUMN "ID_DEMANDE_RETRAIT" ADD GENERATED BY DEFAULT AS IDENTITY;
    SELECT COALESCE(MAX("ID_DEMANDE_RETRAIT"), 0) + 1 INTO nextid FROM t_demande_retrait;
    EXECUTE format('ALTER TABLE t_demande_retrait ALTER COLUMN "ID_DEMANDE_RETRAIT" RESTART WITH %s', nextid);
END $$;
