-- Migration manuelle (PostgreSQL / pgAdmin) — pas de Flyway (cf. CLAUDE.md).
-- Contexte : D6 — l'ID d'une vérification devient AUTO-GÉNÉRÉ côté SGBD (fin du PK fourni par le
-- client, anti-pattern). t_verification.ID_VERIFICATION passe en colonne IDENTITY.
-- La séquence interne est auto-dimensionnée au-delà des ID existants (évite les collisions).
-- À appliquer AVANT le déploiement du code @GeneratedValue (sinon INSERT sans ID → NOT NULL).

DO $$
DECLARE nextid bigint;
BEGIN
    ALTER TABLE t_verification
        ALTER COLUMN "ID_VERIFICATION" ADD GENERATED BY DEFAULT AS IDENTITY;
    SELECT COALESCE(MAX("ID_VERIFICATION"), 0) + 1 INTO nextid FROM t_verification;
    EXECUTE format('ALTER TABLE t_verification ALTER COLUMN "ID_VERIFICATION" RESTART WITH %s', nextid);
END $$;
