-- 2026-06-29 — Trace de lecture des lettres de renvoi par la PRMP (t_lettre_renvoi_lue).
-- La table est créée par Hibernate (ddl-auto) depuis l'entité LettreRenvoiLue : PK IDENTITY
-- ID_LECTURE, ID_LETTRE/ID_PRMP NOT NULL, DATE_LECTURE TIMESTAMP NOT NULL, UNIQUE(ID_LETTRE, ID_PRMP).
-- Ce script (idempotent) garantit l'existence de la table sur une base neuve et ajoute la contrainte
-- FK vers t_lettre_renvoi (non générée par l'entité, qui ne déclare pas d'association).
-- NB : référence H2 (tests) non concernée — schéma recréé depuis les entités (sans cette FK).

CREATE TABLE IF NOT EXISTS t_lettre_renvoi_lue (
    "ID_LECTURE"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_LETTRE"    INTEGER       NOT NULL,
    "ID_PRMP"      VARCHAR(10)   NOT NULL,
    "DATE_LECTURE" TIMESTAMP     NOT NULL,
    CONSTRAINT uk_lettre_lue UNIQUE ("ID_LETTRE", "ID_PRMP")
);

-- FK vers t_lettre_renvoi (ajoutée si absente).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lettre_lue_lettre') THEN
        ALTER TABLE t_lettre_renvoi_lue
            ADD CONSTRAINT fk_lettre_lue_lettre
            FOREIGN KEY ("ID_LETTRE") REFERENCES t_lettre_renvoi("ID_LETTRE");
    END IF;
END $$;

-- Réversion :
-- DROP TABLE IF EXISTS t_lettre_renvoi_lue;
