-- 2026-06-30 — Dernière consultation de l'écran « Demandes de retrait » par la PRMP
-- (t_demande_retrait_vue). Sert à compter les demandes passées à ACCEPTEE/REFUSEE depuis la
-- dernière ouverture de l'écran (compteur demandesRetraitNouvelles du menu PRMP).
--
-- La table est créée par Hibernate (ddl-auto) depuis l'entité DemandeRetraitVue : PK IDENTITY
-- ID_VUE, ID_PRMP NOT NULL UNIQUE, DATE_DERNIERE_VUE TIMESTAMP NOT NULL. Ce script (idempotent)
-- garantit son existence sur une base neuve.
--
-- ⚠️ Aucune colonne « date_traitement » ajoutée à t_demande_retrait : la date de décision existe
--    déjà (DATE_DECISION, posée par accepter()/refuser()) — c'est elle qui est comparée au seuil.
-- NB : référence H2 (tests) non concernée — schéma recréé depuis les entités.

CREATE TABLE IF NOT EXISTS t_demande_retrait_vue (
    "ID_VUE"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_PRMP"           VARCHAR(10) NOT NULL,
    "DATE_DERNIERE_VUE" TIMESTAMP   NOT NULL,
    CONSTRAINT uk_demande_retrait_vue_prmp UNIQUE ("ID_PRMP")
);

-- Réversion :
-- DROP TABLE IF EXISTS t_demande_retrait_vue;
